theme = "kanagawa"

[editor]
line-number = "relative"
bufferline = "multiple"
true-color = true
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = ["selections", "position", "file-encoding", "file-type"]

[editor.cursor-shape]
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
A-h = "move_char_left"
A-j = "move_line_down"
A-k = "move_line_up"
A-l = "move_char_right"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
# Move cursor in insert mode
A-h = "move_char_left"
A-j = "move_line_down"
A-k = "move_line_up"
A-l = "move_char_right"
