[[language]]
name = "markdown"
language-server = { command = "$(which ltex-ls)" }
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []

[[language]]
name = "blade-formatter"
scope = "source.blade-formatter"
roots = []
file-types = ["blade.php"]
language-server = { command = "blade-formatter", args = ["--write"] }
formatter = { command = "blade-formatter", args = ["--write"] }

[[language]]
name = "tailwindcss"
scope = "source.css"
injection-regex = "(postcss|css|html)"
file-types = ["css"]
roots = ["tailwind.config.js","tailwind.config.cjs"]
language-server = { command = "tailwindcss-language-server", args = ["-vvv", "--stdio"] }
config = { }

# [[language]]
# name = "javascript"
# shebangs = ["deno", "node"]
# roots = ["deno.json", "package.json", "tsconfig.json"]
# config = { enable = true, lint = true, unstable = true }
# language-server = { command = "deno", args = ["lsp"], language-id = "javascript" }

# [[language]]
# name = "jsx"
# shebangs = ["deno", "node"]
# roots = ["deno.json", "package.json", "tsconfig.json"]
# config = { enable = true, lint = true, unstable = true }
# language-server = { command = "deno", args = ["lsp"], language-id = "javascriptreact" }

# [[language]]
# name = "typescript"
# shebangs = ["deno", "node"]
# roots = ["deno.json", "package.json", "tsconfig.json"]
# config = { enable = true, lint = true, unstable = true }
# language-server = { command = "deno", args = ["lsp"], language-id = "typescript" }

# [[language]]
# name = "tsx"
# shebangs = ["deno", "node"]
# roots = ["deno.json", "package.json", "tsconfig.json"]
# config = { enable = true, lint = true, unstable = true }
# language-server = { command = "deno", args = ["lsp"], language-id = "typescriptreact" }

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} # <- this is the important line

