version: "3.9"
name: local-dev-services
services:
  # MYSQL Service
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - default-net
    # You may enable the following, if authentication plugin doesnt work
    # command: "--authentication_policy=mysql_native_password"
    environment:
      # MYSQL_DATABASE: mydb
      # MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    healthcheck:
      retries: 10
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
    # Very fast io performance
    tmpfs:
      - /var/lib/mysql
    # Volumes have a slow io performance, known issue!
    # volumes:
    #   - ./mysql-data:/var/lib/mysql:delegated
    #   - ./mysql-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 800M
        reservations:
          cpus: "4"
          memory: 600M
  # ======================
  # PostgreSQL Service
  # postgres:
  #   image: postgres:14.1-alpine
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   networks:
  #     - default-net
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRESQL_DATABASE: mydb
  #   # Very fast io performance
  #   tmpfs:
  #     - /var/lib/postgresql/data
  #   # Volumes have a slow io performance, known issue!
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #     - ./postgres-data/init.sql:/docker-entrypoint-initdb.d/init.sql # If you want to have a init query
  # ======================
  # Redis Caching Service
  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   networks:
  #     - default-net
  #   command: redis-server --save 20 1 --loglevel warning --requirepass password
  #   volumes:
  #     - ./redis-data:/data
  # ======================
  # Email Testing Service
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8225:8025"
    restart: unless-stopped
    networks:
      - default-net
    environment:
      MP_DATA_FILE: /home
    volumes:
      - ./mailpit-data:/home
  # ======================
  # Email Testing Server
  # mailhog:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - "1025:1025"
  #     - "8225:8025"
  #   networks:
  #     - default-net
  #   restart: on-failure
  # ======================
  # PhpMyAdmin to manage database with GUI
  phpmyadmin:
    depends_on:
      - mysql
    # Save your eyes with this lightweight image, or enable the official one
    image: beeyev/phpmyadmin-lightweight:latest
    # image: phpmyadmin
    tty: true
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - default-net
    environment:
      TZ: CET
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ""
  # ======================
  # ZooKeeper to manage services such as Kafka
  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2182:2181"
    networks:
      - default-net
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
  # ======================
  # Kafka
  # More at: https://github.com/bitnami/containers/tree/main/bitnami/kafka
  kafka:
    depends_on:
      - zookeeper
    image: "bitnami/kafka:latest"
    ports:
      - 19092:19092
    networks:
      - default-net
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
# Enable network for Windows
# Linux does't need separate network
# ==========================
networks:
  default-net:
    driver: bridge
