# Keep structured file listings available alongside the familiar Eza aliases.
alias nu-ls = ls
alias ls = ^eza -a --icons --git --group-directories-first
alias lls = ^eza -al --icons --git --group-directories-first
alias la = ^eza -al --icons --git --group-directories-first --git-ignore
alias tree = ^eza -al --icons --git --group-directories-first --tree --git-ignore
alias v = ^nvim
alias lz = ^lazygit
alias dz = ^lazydocker
alias hd = ^herdr
alias kz = ^k9s --readonly
alias kzf = ^k9s --write
alias rgpg = ^gpgconf --reload gpg-agent
alias encgpg = ^gpg --encrypt --armor -r
alias decgpg = ^gpg --decrypt
alias cls = clear
alias mkp = ^mkdir -pv
alias pa = ^php artisan
alias cr = ^composer run
alias cio = ^composer install -o
alias cuo = ^composer update -o
alias cdo = ^composer dump-autoload -o
alias dc = ^docker compose
alias onesync = ^onedrive --sync --verbose --force
alias oneup = ^onedrive --sync --verbose --force --upload-only
alias onedown = ^onedrive --sync --verbose --force --download-only
alias oneshare = ^onedrive --create-share-link
alias onestatus = ^onedrive --display-sync-status
alias gcls = ^git clone --single-branch --branch
# Common Oh My Zsh git shortcuts. Nushell's `ls`, `open`, etc. are separate commands.
alias g = ^git
alias ga = ^git add
alias gaa = ^git add --all
alias gb = ^git branch
alias gba = ^git branch --all
alias gco = ^git checkout
alias gcb = ^git checkout -b
alias gcm = ^git checkout main
alias gc = ^git commit -v
alias gcmsg = ^git commit -m
alias gd = ^git diff
alias gds = ^git diff --staged
alias gf = ^git fetch
alias gl = ^git pull
alias gp = ^git push
alias gst = ^git status
alias gss = ^git status --short
alias glog = ^git log --oneline --decorate --graph
alias gsta = ^git stash push
alias gstp = ^git stash pop
alias grb = ^git rebase
alias grh = ^git reset
alias grhh = ^git reset --hard
alias gcl = ^git clone --recurse-submodules
alias t = ^tmux
alias ta = ^tmux attach
alias tls = ^tmux list-sessions
