return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      -- add tsx and treesitter
      vim.list_extend(opts.ensure_installed, {
        -- Some are disabled due to comes with lazyvim plugins
        "c",
        "cpp",
        "graphql",
        "java",
        "bash",
        "blade",
        "comment",
        "css",
        "dockerfile",
        "git_rebase",
        "gitattributes",
        "gitignore",
        -- "go",
        -- "gomod",
        -- "gowork",
        -- "gosum",
        "html",
        "http",
        "javascript",
        -- "json",
        "lua",
        "markdown_inline",
        "markdown",
        "php",
        "phpdoc",
        "prisma",
        -- "python",
        "rust",
        "scss",
        "sql",
        "svelte",
        "query",
        "regex",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "zig",
      })
    end,
  },
}
