return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      { "nushell/tree-sitter-nu" },
    },
    opts = {
      ensure_installed = {
        -- Some are disabled due to comes with lazyvim plugins
        "c",
        "cpp",
        "graphql",
        "java",
        "bash",
        "blade", -- Manual Installation
        "comment",
        "css",
        "dockerfile",
        "git_rebase",
        "gitattributes",
        "gitignore",
        -- "go",
        -- "gomod",
        -- "gowork",
        -- "gosum",
        "html",
        "http",
        "javascript",
        -- "json",
        "lua",
        "markdown",
        "markdown_inline",
        "nu", -- manual installation, queries = https://github.com/nushell/tree-sitter-nu/blob/main/installation/neovim.md
        -- "puppet",
        "php",
        "phpdoc",
        "prisma",
        -- "python",
        "rust",
        "scss",
        -- "terraform",
        -- "hcl",
        "sql",
        "svelte",
        "query",
        "regex",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
        "zig",
      },
    },
  },
}
