return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      -- Use vim-blade's indentation while Treesitter handles highlighting.
      indent = { enable = true, disable = { "blade" } },
      ensure_installed = {
        -- Additional languages are cheap until a buffer uses their parser.
        -- LazyVim merges these with the parsers supplied by language extras.
        "c",
        "cpp",
        "graphql",
        "java",
        "bash",
        "blade",
        "comment",
        "css",
        "dockerfile",
        "git_rebase",
        "gitattributes",
        "gitignore",
        -- "go",
        -- "gomod",
        -- "gowork",
        -- "gosum",
        "html",
        "http",
        "javascript",
        -- "json",
        "lua",
        "markdown",
        "markdown_inline",
        "nu",
        "puppet",
        "php",
        "php_only", -- PHP expressions injected into Blade templates
        "phpdoc",
        "prisma",
        "python",
        "rust",
        "scss",
        -- "terraform",
        -- "hcl",
        "sql",
        "svelte",
        "query",
        "regex",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
        "zig",
      },
    },
  },
}
