name: "db-dev"
services:
  # MYSQL Service
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    restart: "always"
    networks:
      - db-net
    # You may enable the following, if authentication plugin doesnt work
    # command: "--authentication_policy=mysql_native_password"
    environment:
      # MYSQL_DATABASE: mydb
      # MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    healthcheck:
      retries: 10
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: "10s"
    # Very fast io performance
    tmpfs:
      - /var/lib/mysql
    # Binding is better than typical volume mounting, but create mysql-data dir first.
    # volumes:
    #   - type: "bind"
    #     source: "./mysql-data"
    #     target: "/var/lib/mysql"
    # Volumes have a slow io performance, known issue!
    # volumes:
    #   - ./mysql-data:/var/lib/mysql:delegated
    #   - ./mysql-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "800M"
        reservations:
          cpus: "4"
          memory: "600M"
  # ======================
  # PostgreSQL Service
  # postgres:
  #   image: postgres:14.1-alpine
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   networks:
  #     - db-net
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRESQL_DATABASE: mydb
  #  # Very fast io performance
  #   tmpfs:
  #     - /var/lib/postgresql/data
  #  # Volumes have a slow io performance, known issue!
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #     - ./postgres-data/init.sql:/docker-entrypoint-initdb.d/init.sql  # If you want to have a init query
  # ======================
  # PhpMyAdmin to manage database with GUI
  phpmyadmin:
    depends_on:
      - mysql
    # Save your eyes with this lightweight image, or enable the official one
    image: "beeyev/phpmyadmin-lightweight:latest"
    # image: phpmyadmin
    tty: true
    ports:
      - "8080:80"
    restart: "unless-stopped"
    networks:
      - "db-net"
    environment:
      TZ: "CET"
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: ""
networks:
  db-net:
    driver: "bridge"
