name: "mongodb"
services:
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    networks:
      - net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - "8081:8081"
    networks:
      - net
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
networks:
  net:
    driver: "bridge"
