code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension adrianwilczynski.alpine-js-intellisense
code --install-extension adrianwilczynski.namespace
code --install-extension adrolli.tallui-laravel-livewire-tailwind
code --install-extension ahinkle.laravel-model-snippets
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension akamud.vscode-theme-onedark
code --install-extension albert.TabOut
code --install-extension aldijav.golangwithdidi
code --install-extension alefragnani.project-manager
code --install-extension almenon.arepl
code --install-extension amiralizadeh9480.flutter-widget-wrap
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension amlovey.shaderlabvscodefree
code --install-extension Angular.ng-template
code --install-extension apollographql.vscode-apollo
code --install-extension arcanis.vscode-zipfs
code --install-extension austenc.laravel-docs
code --install-extension austenc.livewire-docs
code --install-extension austenc.tailwind-docs
code --install-extension bebo925.livewire-switcher
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension brittanychiang.halcyon-vscode
code --install-extension bungcip.better-toml
code --install-extension burkeholland.simple-react-snippets
code --install-extension Cardinal90.multi-cursor-case-preserve
code --install-extension cemuka.unity-code-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cierra.livewire-vscode
code --install-extension circlecodesolution.ccs-flutter-color
code --install-extension ClemensPeters.format-json
code --install-extension codezombiech.gitignore
code --install-extension codingyu.laravel-goto-view
code --install-extension ctcuff.font-preview
code --install-extension dansysanalyst.pest-snippets
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-faker
code --install-extension denoland.vscode-deno
code --install-extension DEVSENSE.profiler-php-vscode
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension dustypomerleau.rust-syntax
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension enkia.tokyo-night
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension fernandoescolar.vscode-solution-explorer
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension Fudge.auto-using
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension Gruntfuggly.todo-tree
code --install-extension hajdaini.select-until-pattern
code --install-extension hakcorp.php-awesome-snippets
code --install-extension heybourn.headwind
code --install-extension hiukky.flate
code --install-extension honnamkuan.golang-snippets
code --install-extension humao.rest-client
code --install-extension ikappas.composer
code --install-extension JakeWilson.vscode-placeholder-images
code --install-extension johnpapa.Angular2
code --install-extension jprestidge.theme-material-theme
code --install-extension junstyle.php-cs-fixer
code --install-extension kleber-swf.unity-code-snippets
code --install-extension kokororin.vscode-phpfmt
code --install-extension laurencebahiirwa.deno-std-lib-snippets
code --install-extension leizongmin.node-module-intellisense
code --install-extension lennardv.livewire-goto-updated
code --install-extension linyang95.php-symbols
code --install-extension lorenzopirro.zig-snippets
code --install-extension m1guelpf.better-pest
code --install-extension mathematic.vscode-pdf
code --install-extension MehediDracula.php-constructor
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension mikestead.dotenv
code --install-extension millsp.material-candy
code --install-extension mohamedbenhida.laravel-intellisense
code --install-extension mquandalle.graphql
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.color-highlight
code --install-extension neilbrayfield.php-docblocker
code --install-extension nhoizey.gremlins
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel5-snippets
code --install-extension open-southeners.laravel-pint
code --install-extension PascalReitermann93.vscode-yaml-sort
code --install-extension patbenatar.advanced-new-file
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension PKief.material-icon-theme
code --install-extension premparihar.gotestexplorer
code --install-extension Prisma.prisma
code --install-extension quicktype.quicktype
code --install-extension qwtel.sqlite-viewer
code --install-extension rangav.vscode-thunder-client
code --install-extension raynigon.nginx-formatter
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-community-server-connector
code --install-extension redhat.vscode-rsp-ui
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension Remisa.shellman
code --install-extension ritwickdey.LiveServer
code --install-extension roonie007.hide-files
code --install-extension rubbersheep.gi
code --install-extension rust-lang.rust-analyzer
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension ryannaddy.laravel-artisan
code --install-extension serayuzgur.crates
code --install-extension sevavietl.php-files
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shufo.vscode-blade-formatter
code --install-extension sleistner.vscode-fileutils
code --install-extension slevesque.shader
code --install-extension smcpeak.default-keys-windows
code --install-extension sperovita.alpinejs-syntax-highlight
code --install-extension stpn.vscode-graphql
code --install-extension sumneko.lua
code --install-extension syler.sass-indented
code --install-extension tinkertrain.theme-panda
code --install-extension tonybaloney.vscode-pets
code --install-extension twxs.cmake
code --install-extension usernamehw.errorlens
code --install-extension vadimcn.vscode-lldb
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vuhrmeister.vscode-meteor
code --install-extension waderyan.gitblame
code --install-extension WallabyJs.quokka-vscode
code --install-extension WillettsTech.willetts-tech
code --install-extension wk-j.save-and-run
code --install-extension wmaurer.change-case
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xdebug.php-debug
code --install-extension YclepticStudios.unity-snippets
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
code --install-extension ziglang.vscode-zig
code --install-extension ziyasal.vscode-open-in-github
code --install-extension zobo.php-intellisense
code --install-extension zxh404.vscode-proto3
