#!/bin/sh

code --install-extension adpyke.codesnap
code --install-extension adrianwilczynski.alpine-js-intellisense
code --install-extension adrolli.tallui-laravel-livewire-tailwind
code --install-extension ahinkle.laravel-model-snippets
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension aldijav.golangwithdidi
code --install-extension alefragnani.project-manager
code --install-extension almenon.arepl
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension apollographql.vscode-apollo
code --install-extension arcanis.vscode-zipfs
code --install-extension austenc.laravel-docs
code --install-extension austenc.livewire-docs
code --install-extension austenc.tailwind-docs
code --install-extension bebo925.livewire-switcher
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bourhaouta.tailwindshades
code --install-extension bradlc.vscode-tailwindcss
code --install-extension bungcip.better-toml
code --install-extension burkeholland.simple-react-snippets
code --install-extension Cardinal90.multi-cursor-case-preserve
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cierra.livewire-vscode
code --install-extension ClemensPeters.format-json
code --install-extension codezombiech.gitignore
code --install-extension codingyu.laravel-goto-view
code --install-extension dansysanalyst.pest-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hajdaini.select-until-pattern
code --install-extension ikappas.composer
code --install-extension JakeWilson.vscode-placeholder-images
code --install-extension kamikillerto.vscode-colorize
code --install-extension kokororin.vscode-phpfmt
code --install-extension leizongmin.node-module-intellisense
code --install-extension lennardv.livewire-goto-updated
code --install-extension linyang95.php-symbols
code --install-extension mathematic.vscode-pdf
code --install-extension MehediDracula.php-constructor
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension mohamedbenhida.laravel-intellisense
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension naumovs.color-highlight
code --install-extension neilbrayfield.php-docblocker
code --install-extension nhoizey.gremlins
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel5-snippets
code --install-extension open-southeners.laravel-pint
code --install-extension PascalReitermann93.vscode-yaml-sort
code --install-extension patbenatar.advanced-new-file
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension pranaygp.vscode-css-peek
code --install-extension premparihar.gotestexplorer
code --install-extension Prisma.prisma
code --install-extension quicktype.quicktype
code --install-extension rangav.vscode-thunder-client
code --install-extension raynigon.nginx-formatter
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension roonie007.hide-files
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension ryannaddy.laravel-artisan
code --install-extension sevavietl.php-files
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shufo.vscode-blade-formatter
code --install-extension sleistner.vscode-fileutils
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WallabyJs.quokka-vscode
code --install-extension wk-j.save-and-run
code --install-extension xdebug.php-debug
code --install-extension yzhang.markdown-all-in-one
code --install-extension ziyasal.vscode-open-in-github
code --install-extension zobo.php-intellisense
code --install-extension zxh404.vscode-proto3
