version: "3.8"
name: dev
services:
  # Database service
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    # networks:
    #   - webnet
    command: "--authentication_policy=mysql_native_password"
    environment:
      MYSQL_DATABASE: mydb
      # MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      retries: 10
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
    volumes:
      - ./db-data:/var/lib/mysql
  # ======================
  # Email Testing Server
  mailpit:
    image: axllent/mailpit
    # networks:
    #   - webnet
    ports:
      - "1025:1025"
      - "8225:8025"
    environment:
      MP_DATA_FILE: /home
    volumes:
      - ./mailpit:/home
    restart: unless-stopped
  # ======================
  # Email Testing Server
  # mailhog:
  #   image: mailhog/mailhog:latest
  #   networks:
  #     - webnet
  #   ports:
  #     - "1025:1025"
  #     - "8225:8025"
  #   restart: on-failure
  # ======================
  # PhpMyAdmin to manage database with UI
  phpmyadmin:
    depends_on:
      - db
    # Save your eyes with this lightweight image, or enable the official one
    image: beeyev/phpmyadmin-lightweight:latest
    # image: phpmyadmin
    tty: true
    # networks:
    #   - webnet
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - TZ=CET
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_HOST=db

# Enable network for Windows
# Linux does't need separate network
# ==========================
# networks:
#   webnet:
#     driver: bridge
