name: "local-dev"
services:
  # ======================
  # Redis Caching Service
  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   networks:
  #     - default-net
  #   command: redis-server --save 20 1 --loglevel warning --requirepass password
  #   volumes:
  #     - ./redis-data:/data
  # =======================
  # Cassandra DB
  # Takes a while to boot up like 6s
  cass:
    image: cassandra:latest
    restart: on-failure
    ports:
      - "19042:9042"
    # Run this command after booting to create a keyspace
    # command: |
    #	echo "CREATE KEYSPACE dev WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : 1 };" | cqlsh
    networks:
      - default-net
# Enable network for Windows
# Linux doesn't need separate network
# ==========================
networks:
  default-net:
    driver: "bridge"
