--ozone-platform=wayland
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoEncoder,VaapiIgnoreDriverChecks,UseOzonePlatform,WaylandWindowDecorations
--use-gl=angle
--use-angle=vulkan
--enable-gpu-rasterization
--enable-zero-copy
--ignore-gpu-blocklist
--disable-features=UseChromeOSDirectVideoDecoder
